# Generated by Django 3.2.25 on 2024-04-19 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20240419_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='gategory',
            new_name='category',
        ),
    ]
